### ISSUE TITLE
Question: Inherit body parameters on POST request

### ISSUE THREAD

**Issue by Sh4d1** [apicase/services#2]
Hey!

I'm trying to use your library ( looks very promising btw :smile: ) and I have a question.

All my APIs calls are to the same endpoint `/rpc` and the body may look like that:
```
{
  service: "user",
  method: "UserService.Auth",
  request: {
    name: ...
    ...
  }
}
```
with the service and method changing depending of which service and method I want to call. So I was wondering if I can define a service, let's say `CreateUser` which will take the name, email and password but will automatically add the `service` and `method` fields in the body. I did not find any answer to the question in the docs.

Best,

Patrik

**Comment by Kelin2025** [comment]
Hi Patrik!  
1. `body` should be put inside `body` property:
```javascript
{
  body: {
    /* ... */
  }
}
```

2. `body` has no merge strategy. It's just overwritten because it's not obvious.  
But you can play with hooks and meta, doing smth like this in the parent service:
```javascript
/* Root service */
const Root = {
  hooks: {
    before ({ payload, meta, next }) {
      const body = {
        service: meta.service,
        method: meta.method,
        request: payload.body
      }
      next({ ...payload, body })
    }
  }
})

/* Services tree */
const API = new ApiTree(Root, [
  { 
    name: 'auth',
    method: 'POST',    // Request method (I think it may confuse)
    meta: {
      service: 'user',
      method: 'UserService.Auth'
    }
  }
])

/* Request example */
API('auth', {
  body: {
    name: ...,
    /* smth that will be passed to body.request */
  }
})
```

3. To make it simpler, we can add some helper function:
```javascript
const rpc = (service, method, additional = {}) => ({
  ...data,
  name: method,
  meta: { service, method }
})
```
Then
```javascript
new ApiTree(Root, [
  /* The same as before but shorter and service name === rpc service name */
  rpc('user', 'UserService.Auth', {
    /* extra data here (optional) */
  })
])
```

**Comment by Sh4d1** [comment]
Hey perfect thanks :) 

I also was wondering if the services can return promises ?

**Comment by Kelin2025** [comment]
You mean ApiTree? It's quite easy:
```javascript
API('someService', payload) === API('someService').doRequest(payload)
```
