### ISSUE TITLE
How to set headers

### ISSUE THREAD

**Issue by waghcwb** [apicase/services#5]
How can I set default headers for my requests?

I've tried setting the header in `BaseService` and `ApiTree` requests, but didn't work.
```js
export const BaseService = new ApiService({
  adapter: fetch,
  url: 'https://my-api-url.com',
  mode: 'no-cors',
  headers: {
    'app-key': process.env.APP_KEY,
  },
})
  .on('error', globalErrorLogger)
  .on('done', logSuccess)
  .on('fail', logFailure)

export const api = new ApiTree(BaseService, [
  {
    url: 'commerce/v1',
    children: [
      {
        name: 'checkAvailability',
        url: 'checkAvailability',
        method: 'GET',
        query: { postalCode: 'postalCodeNumber', number: 'addressNumber' }
      },
    ]
  }
])
```

**Comment by Kelin2025** [comment]
I don't think that headers merging feature is a good idea.  
Just because you can't remove 'em for a certain nested service. 

Better use hook instead:
```js
const BaseService = new ApiService({
  hooks: {
    before ({ payload, next }) {
      payload.headers = {
        ...payload.headers,
        'app-key': process.env.APP_KEY
      }
      next(payload)
    }
})
```

Or if you are using libraries like Ramda:
```js
const withAppkey = assoc(['headers', 'app-key'])

const BaseService = new ApiService({
  hooks: {
    before: ({ payload, next }) => next(withAppKey(process.env.APP_KEY)(payload))
  }
})
```

**Comment by waghcwb** [comment]
Hello @Kelin2025, thank you for the quick response.


I'm trying to migrate my api to make use of this plugin.

Today, I'm using [`axios`](https://github.com/axios/axios) and I've two services (commerce and products)

![image](https://user-images.githubusercontent.com/6169950/43235850-7db77c76-9058-11e8-8c1b-9f4c3fa68ec9.png)

I've a base config file
```js
const config = {
  baseURL: process.env.SERVICE_URL,
  responseType: 'json',

  headers: {
    'my-api-key': process.env.API_KEY,
  }
}

export default config
```

And then I extend the base config to create my `axios` instances
```js
import axios from 'axios'
import config from './config'

const commerce = axios.create({
  ...config,
  baseURL: process.env.SERVICE_COMMERCE_URL,

  params: {
    my: 'params'
  }
})

export default commerce
```

Finally I can make the request to the the api.
```js
import commerceService from './commerce'
commerceService .get(url)
```

And the headers are set up..

![image](https://user-images.githubusercontent.com/6169950/43236360-178db5de-905b-11e8-849b-6f5a325fcc97.png)

This is the code of the "new" api.
```js
import { ApiService, ApiTree } from '@apicase/services'
import fetch from '@apicase/adapter-fetch'

export const BaseService = new ApiService({
  adapter: fetch,
  url: process.env.SERVICE_URL,
  mode: 'no-cors',

  hooks: {
    before({ payload, next }) {
      payload.headers = {
        ...payload.headers,
        'app-key': process.env.APP_KEY
      }

      payload.query = {
        ...payload.query,
        'my': 'query'
      }

      next(payload)
    }
  }
})

export const api = new ApiTree(BaseService, [
  {
    url: 'commerce/v1',
    children: [
      {
        name: 'checkAvailability',
        url: 'checkAvailability',
        method: 'GET',
        query: { my: 'query' }, // trying to send this with doRequest..
      },
    ]
  }
])
```

And then..
```js
api('checkAvailability').doRequest()
```

I'm testing this from a localhost env, making the request to the api. The first method connect sucessfully to the microservice and then I can grab the data. But the second one with the `apicase` it fails with 401 Security failure status.

![image](https://user-images.githubusercontent.com/6169950/43236573-3c04de6e-905c-11e8-9fcb-0ae5dcc14dc9.png)

I cannot see the ´app-key´ header on the request.

This is the output of `.on('fail', logFailure)` event. It has the `app-key` setted.
```js
{
  "0": {
    "status": 0,
    "headers": {},
    "body": ""
  },
  "1": {
    "success": false,
    "pending": false,
    "started": true,
    "cancelled": false,
    "payload": {
      "url": "API_URL",
      "mode": "no-cors",
      "method": "GET",
      "query": {
        "my": "query"
      },
      "headers": {
        "app-key": "MY_APP_KEY"
      }
    },
    "result": {
      "status": 0,
      "headers": {},
      "body": ""
    },
    "meta": {}
  }
}
```

Am I doing something wrong? Looks like that the headers are not present on the request.

**Comment by Kelin2025** [comment]
Sorry, but I can take a look on it only in weekends. Now I'm busy, project release soon

**Comment by waghcwb** [comment]
@Kelin2025, 

If you can help me on weekend, no problems 😄

**Comment by Kelin2025** [comment]
The problem was in `no-cors` mode. Without that all headers are sent successfully

Closed
